# Generated by Django 4.2.6 on 2024-01-21 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangalist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangalist', to=settings.AUTH_USER_MODEL),
        ),
    ]
