# Generated by Django 4.2.6 on 2024-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0002_alter_mangalist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
