# Generated by Django 4.2.6 on 2024-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0004_alter_manga_manga_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_name',
            field=models.CharField(max_length=100),
        ),
    ]
