# Generated by Django 4.2.6 on 2024-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0005_alter_manga_manga_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='current_chapter',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
