# Generated by Django 4.2.6 on 2024-01-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0006_manga_current_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='current_chapter',
            field=models.IntegerField(default=0),
        ),
    ]
